### ISSUE TITLE
Compiling with ng build --aot throws  "can't find symbol KeyRegistry exported from module"

### ISSUE THREAD

**Issue by rodneyjoyce** [KillerCodeMonkey/ngx-quill#10]
Using AngularCLI and trying to build in AOT mode, I get this error:  "can't find symbol KeyRegistry exported from module". Honestly at this stage I have no idea what this means or why - I am raising it here in the hope that someone knows what this means - I will post back here if I can figure out the issue

```
>ng build --aot
  0% compilingcan't resolve module C:/Git/QueMesaAdmin/QueMesaAdminApp/node_modules/ngx-quill/node_modules/@angular/core/src/di/reflective_key.d.ts from C:/Git/QueMesaAdmin/QueMesaAdminApp/node_modules/ngx-quill/node_modules/@angular/core/src/di/reflective_key.d.ts
can't find symbol KeyRegistry exported from module C:/Git/QueMesaAdmin/QueMesaAdminApp/node_modules/ngx-quill/node_modules/@angular/core/src/di/reflective_key.d.ts
Error: can't find symbol KeyRegistry exported from module C:/Git/QueMesaAdmin/QueMesaAdminApp/node_modules/ngx-quill/node_modules/@angular/core/src/di/reflective_key.d.ts
    at ReflectorHost.findDeclaration (C:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\reflector_host.ts:200:15)
    at C:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\codegen.ts:179:44
    at Array.forEach (native)
```

**Comment by KillerCodeMonkey** [comment]
maybe this is a windows or old cli issue?

```
angular-cli: 1.0.0-beta.25.5
node: 7.4.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3
```

and

```
"ngx-quill": "^0.2.3"
```
works quite fine:

```
$ ng build --aot
Hash: cbf711759ee3a793a92a                                                               
Time: 6228ms
chunk    {0} main.bundle.js, main.bundle.map (main) 30.9 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.css, styles.bundle.map, styles.bundle.map (styles) 1.77 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 1.87 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
```

**Comment by rodneyjoyce** [comment]
Thanks - you may be right, it might be a SUE. 

I think my global AngularCLI version and my installed version were different - I'll double check now and confirm.

**Comment by rodneyjoyce** [comment]
Yes, you are right, this error is not a problem - however I have a different error - I will open a new issue

**Comment by KillerCodeMonkey** [comment]
nice you get it working
