### ISSUE TITLE
mini-css-extract-plugin compiler error

### ISSUE THREAD

**Issue by astone2014** [KillerCodeMonkey/ngx-quill#1057]
I'm getting really strage behavior when adding styles in my `angular.json` which I think is related to webpack-contrib/mini-css-extract-plugin#186

```json
"options": {
    "styles": [
        "./node_modules/quill/dist/quill.core.css",
        "./node_modules/quill/dist/quill.snow.css",
        "./node_modules/quill/dist/quill.bubble.css",
        "src/styles.scss"
    ],
}
```

Resulting in this error. Only happens on Linux, not windows.

```
ERROR in Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot read property 'replace' of undefined
    at normalizeBackSlashDirection (/home/astone/source/dwview/node_modules/webpack/lib/RequestShortener.js:16:17)
    at new RequestShortener (/home/astone/source/dwview/node_modules/webpack/lib/RequestShortener.js:26:15)
    at new Compiler (/home/astone/source/dwview/node_modules/webpack/lib/Compiler.js:195:27)
    at Compiler.createChildCompiler (/home/astone/source/dwview/node_modules/webpack/lib/Compiler.js:558:25)
    at Compilation.createChildCompiler (/home/astone/source/dwview/node_modules/webpack/lib/Compilation.js:2243:24)
    at Object.pitch (/home/astone/source/dwview/node_modules/mini-css-extract-plugin/dist/loader.js:89:43)
```

If I remove the quill styles the error goes away. Even weirder I'm referencing other CSS from node modules with no issues...

```json
"options": {
    "styles": [
        "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
        "./node_modules/animate.css/animate.min.css",
        "src/styles.scss"
    ],
}
```

```
Angular CLI: 10.1.4
Node: 14.10.1
OS: linux x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    10.2.3
@angular/material               10.2.3
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3
```

**Comment by KillerCodeMonkey** [comment]
why asking it here :D. i am not responsible for this plugin nor the angular cli :D. 

maybe you have a custom webpack config?:
https://github.com/angular/angular-cli/issues/17687
https://github.com/angular/angular-cli/issues/16502

and other topics about this regarding windows:
https://github.com/angular/angular-cli/issues/3225
