### ISSUE TITLE
BUG: ngx-quill doesn't work with Angular Elements

### ISSUE THREAD

**Issue by abf7d** [KillerCodeMonkey/ngx-quill#1481]
I'm building an Angular 13 custom element / web component that uses ngx-quill. Here are the versions for the packages in my package.json:
```
 "ngx-quill": "^16.1.1",
"@angular/elements": "~13.0.2",
"@angular/core": "~13.0.2",
```
I build the web component app using the command: `ng build plots-elements --output-hashing none `. When I navigate to my component in the consuming app I get a blank area where the component is supposed to render and I get the error: 
```
..\..\dist\plots-elements\runtime.js:formatted:194 GET http://localhost:4202/263.js net::ERR_ABORTED 404 (Not Found)
r.l @ ..\..\dist\plots-elements\runtime.js:formatted:194
r.f.j @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
r.e @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
Dm @ ..\..\dist\plots-elements\runtime.js:formatted:194
h @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
ZoneAwarePromise @ zone.js:1387
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
_trySubscribe @ ..\..\dist\plots-elements\runtime.js:formatted:194
subscribe @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
subscribe @ ..\..\dist\plots-elements\runtime.js:formatted:194
ngAfterViewInit @ ..\..\dist\plots-elements\runtime.js:formatted:194
Ig @ ..\..\dist\plots-elements\runtime.js:formatted:194
pg @ ..\..\dist\plots-elements\runtime.js:formatted:194
xa @ ..\..\dist\plots-elements\runtime.js:formatted:194
zo @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
zo @ ..\..\dist\plots-elements\runtime.js:formatted:194
gd @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
zo @ ..\..\dist\plots-elements\runtime.js:formatted:194
gd @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
zo @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
zo @ ..\..\dist\plots-elements\runtime.js:formatted:194
gd @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
zo @ ..\..\dist\plots-elements\runtime.js:formatted:194
gd @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
zo @ ..\..\dist\plots-elements\runtime.js:formatted:194
Mv @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
hd @ ..\..\dist\plots-elements\runtime.js:formatted:194
detectChanges @ ..\..\dist\plots-elements\runtime.js:formatted:194
tick @ ..\..\dist\plots-elements\runtime.js:formatted:194
(anonymous) @ ..\..\dist\plots-elements\runtime.js:formatted:194
invoke @ zone.js:372
onInvoke @ ..\..\dist\plots-elements\runtime.js:formatted:194
invoke @ zone.js:371
run @ zone.js:134
run @ ..\..\dist\plots-elements\runtime.js:formatted:194
next @ ..\..\dist\plots-elements\runtime.js:formatted:194
__tryOrUnsub @ ..\..\dist\plots-elements\runtime.js:formatted:194
next @ ..\..\dist\plots-elements\runtime.js:formatted:194
_next @ ..\..\dist\plots-elements\runtime.js:formatted:194
next @ ..\..\dist\plots-elements\runtime.js:formatted:194
next @ ..\..\dist\plots-elements\runtime.js:formatted:194
emit @ ..\..\dist\plots-elements\runtime.js:formatted:194
dp @ ..\..\dist\plots-elements\runtime.js:formatted:194
ev @ ..\..\dist\plots-elements\runtime.js:formatted:194
onInvokeTask @ ..\..\dist\plots-elements\runtime.js:formatted:194
invokeTask @ zone.js:405
runTask @ zone.js:178
invokeTask @ zone.js:487
invokeTask @ zone.js:1600
globalZoneAwareCallback @ zone.js:1626
Show 32 more frames
2..\..\dist\plots-elements\runtime.js:formatted:194 ERROR ChunkLoadError: Loading chunk 263 failed.
(error: http://localhost:4202/263.js)
    at Object.r.f.j (..\..\dist\plots-elements\runtime.js:formatted:194:NaN)
```
Everything else in my project works. The component works in an Angular app / imported as an Angular library. When it is compiled as an Angular Element and imported into a vanilla js page, it doesn't work. Is there a way to fix this or is there a work around?

**Comment by KillerCodeMonkey** [comment]
I would guess that it tries to load quilljs, because quilljs is loaded
asynchronous and it is not part of your bundled component.

So you have to make sure, that quilljs is available as module.

Aaron Friedman ***@***.***> schrieb am Do., 10. Feb. 2022,
15:57:

**Comment by abf7d** [comment]
I tried importing the quill.min.js file in the angular element project and importing it into the consuming app. I created a very simple component that has only a `<quill-editor></quill-editor>` and nothing renders the editor.

**Comment by KillerCodeMonkey** [comment]
I general I do not know that much about custom elements with angular and
how the build process works if you depend on other modules.

Maybe you can check if you need to handle async module imports there.

Maybe you need to add an importmap to your index html where you can map the
import of "quill" to a qualified path to the quilljs file

Aaron Friedman ***@***.***> schrieb am Do., 10. Feb. 2022,
17:53:

**Comment by abf7d** [comment]
Would you happen to have a quick example or resources on how to do this? I have never turned off async import. Is this whats known as lazy loading? Is there an injection token to use?

**Comment by KillerCodeMonkey** [comment]
Nope check the source code of ngx-quill.
There is an quill-service.
It handles the loading of quilljs. Since quilljs is a large library it
should be loaded only once and only if needed and should work with server
side rendering. This all leads down that the service is loading / importing
quill with async await and makes sure it is done only once. Rxjs and
observables are used to be able to cancel the loading as well.

You could do something unit tests to if you want to mock own or custom
services.

@NgModule({
  providers:[{ provide: QuillService, useClass: MyCustomQuillService }]
})

And your custom service:

class MyQuillService implements Quillservice {

}

Just copy the content of the service but directly import quill at the top
of your file and set the private Quill property to the imported quill
class. Remove the part in the "defer" function where quill is imported and
set to this.Quill

Aaron Friedman ***@***.***> schrieb am Do., 10. Feb. 2022,
21:00:

**Comment by abf7d** [comment]
This looks like a good start. I'll try it out, thanks!

**Comment by abf7d** [comment]
So I created a service and imported as you said.

I imported directly from quill:
`import * as quill  from 'quill';`

I set the Quill property
`private Quill: any = quill;`

I injected the service
`providers: [{provide: QuillService, useClass: SyncQuillService}]`

I added the script file to the angular json to see if that works
` "scripts": [
              "node_modules/quill/dist/quill.min.js"
    ]
```

While debugging, I verified that the ngx-quill was indeed using my service. I verified that the quill was working in my Angular app that cosumed the library. Everything was working. I then built the Angular Elements and ran it, but it did not work. However it was failing at the place where an instance of the Quill class is declared. The error is on this line: https://github.com/KillerCodeMonkey/ngx-quill/blob/06cb86a2fe64a142be02d9eae04fcc3f21ab9b55/projects/ngx-quill/src/lib/quill-editor.component.ts#L293

It look as though it is not finding the script that I imported. Do you have any idea why that would be happening?

**Comment by KillerCodeMonkey** [comment]
what error do you get?

**Comment by abf7d** [comment]
I get:
```ERROR TypeError: e is not a constructor
    at ..\..\dist\plots-elements\main.js:1:592662
    at ZoneDelegate.invoke (zone.js:372:1)
    at Zone.run (zone.js:134:1)
    at Bi.runOutsideAngular (..\..\dist\plots-elements\main.js:1:1031558)
    at w._next (..\..\dist\plots-elements\main.js:1:592482)
    at w.__tryOrUnsub (..\..\dist\plots-elements\main.js:1:428923)
    at w.next (..\..\dist\plots-elements\main.js:1:428028)
    at M._next (..\..\dist\plots-elements\main.js:1:427320)
    at M.next (..\..\dist\plots-elements\main.js:1:427090)
    at M.next (..\..\dist\plots-elements\main.js:1:424851)
```

and when I look at the pretty printed line in main.js, I see:
```
this.zone.runOutsideAngular(()=>{
                            var ne, ce, Ee;
                            if (this.quillEditor = new e(this.editorElem,{
                                bounds: f,
                                debug: _,
                                formats: te,
                                modules: a,
                                placeholder: u,
                                readOnly: U,
                                defaultEmptyValue: P,
                                scrollingContainer: H,
                                strict: this.strict,
                                theme: this.theme || (this.service.config.theme ? this.service.config.theme : "snow")
                            }),
                            this.linkPlaceholder) {
                                const He = null == (ce = null == (ne = this.quillEditor) ? void 0 : ne.theme) ? void 0 : ce.tooltip
                                  , Me = null == (Ee = null == He ? void 0 : He.root) ? void 0 : Ee.querySelector("input[data-link]");
                                (null == Me ? void 0 : Me.dataset) && (Me.dataset.link = this.linkPlaceholder)
                            }
                        }
                        ),
```
When I was playing around with how to import quill, I got the same error (only the code wasn't minified). When I debugged I found that the Quill constructor (here minified to e) was undefined. I take it this meant that quill wasn't importing correctly. Also I forgot to mention above that this is how I commented out the async import of quill in my custom service:
```
 this.document.addEventListener =
      (this.document as any)['__zone_symbol__addEventListener'] || this.document.addEventListener;
    // const quillImport = await import('quill');
    this.document.addEventListener = maybePatchedAddEventListener;

    // this.Quill = (quillImport.default ? quillImport.default : quillImport) as any;
111

**Comment by KillerCodeMonkey** [comment]
Could you share your custom service code?

Aaron Friedman ***@***.***> schrieb am Fr., 11. Feb. 2022,
15:55:

**Comment by abf7d** [comment]
Again, this service works when the component is used in a plain Angular library imported into an Angular app. When it is compiled into a plain js file through Angular Elements, it breaks.

**Comment by KillerCodeMonkey** [comment]
I must say. It looks like how I would do it

Aaron Friedman ***@***.***> schrieb am Fr., 11. Feb. 2022,
16:09:

**Comment by KillerCodeMonkey** [comment]
But then I guess it happens because of quilljs

Another idea: do not import quill in your typescript.

Use window.quill and import the quilljs source from a cdn in the head of
your html file.



Bengt Weiße ***@***.***> schrieb am Fr., 11. Feb. 2022, 16:14:

**Comment by KillerCodeMonkey** [comment]
did you tried my idea to not bundle quilljs in your angular element and use quilljs from then window object?

**Comment by KillerCodeMonkey** [comment]
any updates on this?

**Comment by KillerCodeMonkey** [comment]
Hey. I will close this issue then.

Feel free to reopen it, when you think it is really an issue with ngx-quill

**Comment by jfan0888** [comment]
@KillerCodeMonkey 
I have the same issue.

**Comment by KillerCodeMonkey** [comment]
Since there is nothing I can do or change. I would leave it closed.

Did you tried the things mentioned in the comments above? Overwriting the quill service and using quilljs from the window Object instead of importing it?

In general I have never used angular elements. But if you need an alternative to ngx-quill try stencil-quill. It compiles to a native web component and can be used in angular, but without angular form controls/models.
