### ISSUE TITLE
ERROR TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_2__.__awaiter)

### ISSUE THREAD

**Issue by lookMyCode** [KillerCodeMonkey/ngx-quill#1495]
Hi,

In new projects, I have a this error:

```
core.mjs:6449 ERROR TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_2__.__awaiter) is not a function
    at ngx-quill.mjs:47:44
    at Observable._subscribe (defer.js:5:18)
    at Observable._trySubscribe (Observable.js:37:1)
    at Observable.js:31:1
    at errorContext (errorContext.js:19:1)
    at Observable.subscribe (Observable.js:22:21)
    at share.js:58:21
    at SafeSubscriber.<anonymous> (lift.js:10:1)
    at Observable.js:26:1
    at errorContext (errorContext.js:19:1)
```

Old projects work well.

My `ts.config.json`:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "types": ["google.maps"],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "tslib": ["./node_modules/tslib/tslib.d.ts"]
    }
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

My `package.json`:

```
{
  "name": "...",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.1.2",
    "@angular/cdk": "^12.2.12",
    "@angular/common": "~13.1.2",
    "@angular/compiler": "~13.1.2",
    "@angular/core": "~13.1.2",
    "@angular/forms": "~13.1.2",
    "@angular/localize": "^13.1.2",
    "@angular/material": "^12.2.12",
    "@angular/platform-browser": "~13.1.2",
    "@angular/platform-browser-dynamic": "~13.1.2",
    "@angular/router": "~13.1.2",
    "@angular/service-worker": "~13.1.2",
    "ngx-quill": "^16.0.1",
    "quill": "^1.3.7",
    "rxjs": "^7.4.0",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.3",
    "@angular/cli": "~13.1.3",
    "@angular/compiler-cli": "~13.1.2",
    "@angular/language-service": "~13.1.2",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@types/quill": "^1.3.7",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.7",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "^7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.5.4"
  }
}
```

My `app.module.ts`:

```
...
import { QuillModule } from 'ngx-quill'


@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    BrowserAnimationsModule,
    routing,
    QuillModule.forRoot()
  ],
  declarations: [
		..
  ],
  providers: [
    ...
  ],
  bootstrap: [AppComponent]
})

export class AppModule { }
```

**Comment by KillerCodeMonkey** [comment]
Eeehm I would say. Just checkout my demo repo first, if it is working for
you.

lookMyCode ***@***.***> schrieb am Mi., 2. März 2022, 21:42:

**Comment by lookMyCode** [comment]
Update:

After testing, I realized - I only have the problem with Angular 13, when version 12 - everything works well.

**Comment by KillerCodeMonkey** [comment]
Maybe something while upgrading to angular 13 failed? Because my demo repo
is using angular 13 ;-)

lookMyCode ***@***.***> schrieb am Do., 3. März 2022, 17:30:

**Comment by lookMyCode** [comment]
Tomorrow I will check again, maybe something went wrong

**Comment by KillerCodeMonkey** [comment]
blubb

**Comment by lookMyCode** [comment]
@KillerCodeMonkey  I'm sorry, I didn't have time to check. I'm in touch, if I find a problem I'll let you know
