### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by PoiScript** [KillerCodeMonkey/ngx-quill#163]
Will this package supports Angular 6 and rxjs 6? I'm trying to update my application now. :)

**Comment by KillerCodeMonkey** [comment]
it will, but when it is final ;)

**Comment by josepfdc** [comment]
No work in angular cli 6... please !!!! could you fix it !

Thank you !!!

**Comment by KillerCodeMonkey** [comment]
It would be nice if you would share a more specific description of the error... instead of a message  without any content and multiple "!" ;)

**Comment by elias-garcia** [comment]
Hi! This is the error in Angular 6:

```
ERROR in ./node_modules/ngx-quill-editor/index.ts
Module build failed: Error: /Users/elias/Documents/agora-binaria/eduhostalaria/client/node_modules/ngx-quill-editor/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/elias/Documents/agora-binaria/eduhostalaria/client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:708:23)
    at plugin.done.then (/Users/elias/Documents/agora-binaria/eduhostalaria/client/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by bop10** [comment]
There is a problem when you try to update rxjs (Angular 6 requires rxjs 6) too:

```
Package "ngx-quill" has an incompatible peer dependency to "rxjs" (requires "^5.5.2", would install "6.1.0").
Incompatible peer dependencies found. See above.
```

**Comment by KillerCodeMonkey** [comment]
feel free to test a beta-release 3.0.0-1 updated only the dependencies. i have to check if it is really working :)

**Comment by elias-garcia** [comment]
I will give it a try in a few minutes! 😄 @KillerCodeMonkey

**Comment by KillerCodeMonkey** [comment]
3.0.0 released it is working for me, tested with latest angular cli (ng serve is working) build of --prod --aot runs without errors

**Comment by elias-garcia** [comment]
Also working for me, thanks a lot! 👍
