### ISSUE TITLE
Bug with standalone api + reactive form ?

### ISSUE THREAD

**Issue by evan-boissonnot** [KillerCodeMonkey/ngx-quill#1664]
Hi

In a v15 angular project, we try to use quill editor

const providers: Array<Provider | EnvironmentProviders> = [
importProvidersFrom(
    QuillModule.forRoot()
)
]
bootstrapApplication(AppComponent, { providers })

When we try to use quill editor on a standalone component 
@Component({
  selector: 'cvgamify-quill-test',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './quill-test.component.html',
  styleUrls: ['./quill-test.component.less']
})
export class QuillTestComponent {
  private fb = inject(FormBuilder);
  form = this.fb.group({
    description: new FormControl('', Validators.required)
  })
}

and html
<form [formGroup]="form">
    <quill-editor formControlName="description"></quill-editor>
</form>

We got this error :
ERROR Error: NG01203: No value accessor for form control name: 'description'. Find more at https://angular.io/errors/NG01203
    at _throwMissingValueAccessorError (forms.mjs:3165:11)
    at setUpControl (forms.mjs:2938:13)
    at FormGroupDirective.addControl (forms.mjs:4745:9)
    at FormControlName._setUpControl (forms.mjs:5295:43)
    at FormControlName.ngOnChanges (forms.mjs:5240:18)
    at FormControlName.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1574:14)
    at callHook (core.mjs:2498:18)
    at callHooks (core.mjs:2457:17)
    at executeInitAndCheckHooks (core.mjs:2408:9)
    at refreshView (core.mjs:10434:21)

**Comment by KillerCodeMonkey** [comment]
could you please create a stackblitz/codepen or what ever online demo?

**Comment by KillerCodeMonkey** [comment]
As far as i understand will `importProvidersFrom` import the providers and not the components.

So you need to add `QuillModule` to the components imports:
`imports: [CommonModule, ReactiveFormsModule, Quillmodule],`
