### ISSUE TITLE
Problems with unit testing in Karma

### ISSUE THREAD

**Issue by sguin3395** [KillerCodeMonkey/ngx-quill#1704]
```
beforeEach(waitForAsync(() => {

TestBed.configureTestingModule({
  declarations: [ JobCommentsComponent ],
  imports: [
    TestHelperModule,
    AngularMaterialIntegrationModule,
    QuillModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader, useClass: TranslateLoaderFactoryMock
      }
    })
  ],
  providers: [
    { provide: DomSanitizer, useValue: sanitizerMock },
    QuillModule.forRoot().providers
  ],
  schemas: [
    NO_ERRORS_SCHEMA,
  ],
})
.compileComponents();
}));

beforeEach(() => {
fixture = TestBed.createComponent(JobCommentsComponent);
component = fixture.componentInstance;
});

beforeEach(inject([Store], (store: Store) => {
storeMock = store;
storeCallFake = new StoreCallFake(storeMock);
storeCallFake.spyOn();
}));

it('should create', () => {
fixture.detectChanges();
expect(component).toBeTruthy();
});
```

That is the code in my spec.ts file and I'm running it with Karma

However, I keep encountering this issue

`TypeError: injector.get is not a function at new QuillService (http://localhost:9876/_karma_webpack_/vendor.js:392238:30) at Object.QuillService_Factory [as factory] (http://localhost:9876/_karma_webpack_/vendor.js:392277:10) at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/vendor.js:288126:29) at R3Injector.get (http://localhost:9876/_karma_webpack_/vendor.js:288027:23) at ChainedInjector.get (http://localhost:9876/_karma_webpack_/vendor.js:292050:32) at lookupTokenUsingModuleInjector (http://localhost:9876/_karma_webpack_/vendor.js:283487:31) at getOrCreateInjectable (http://localhost:9876/_karma_webpack_/vendor.js:283530:10) at Module.ɵɵdirectiveInject (http://localhost:9876/_karma_webpack_/vendor.js:290084:10) at NodeInjectorFactory.QuillEditorComponent_Factory [as factory] (http://localhost:9876/_karma_webpack_/vendor.js:392990:961) at getNodeInjectable (http://localhost:9876/_karma_webpack_/vendor.js:283701:38)`

**Comment by sguin3395** [comment]
`import { Injector } from '@angular/core';
import { Observable } from 'rxjs';
import { QuillConfig, CustomModule } from 'ngx-quill/config';
import * as i0 from "@angular/core";
export declare class QuillService {
    config: QuillConfig;
    private Quill;
    private document;
    private quill$;
    constructor(injector: Injector, config: QuillConfig);
    getQuill(): Observable<any>;
    /**
     * Marked as internal so it won't be available for `ngx-quill` consumers, this is only
     * internal method to be used within the library.
     *
     * @internal
     */
    registerCustomModules(Quill: any, customModules: CustomModule[] | undefined, suppressGlobalRegisterWarning?: boolean): Promise<any>;
    static ɵfac: i0.ɵɵFactoryDeclaration<QuillService, [null, { optional: true; }]>;
    static ɵprov: i0.ɵɵInjectableDeclaration<QuillService>;
}`

this is my quill.service.d.ts which comes in with **node_modules/ngx-quill/lib**

**Comment by KillerCodeMonkey** [comment]
which angular and ngx-quill version do you use?

**Comment by sguin3395** [comment]
```
{
  "name": "machiningcloud",
  "version": "3.6.1",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph --base=remotes/origin/feature/NG8_Migration",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "update:check": "ng update",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "testa": "yarn && ng test accounts",
    "servea": "yarn && ng serve accounts",
    "servewa": "set NODE_OPTIONS=--max_old_space_size=8192 && yarn && ng serve mc-web-app",
    "serveli": "yarn && ng serve mc-libs-integration",
    "dist-build-li-build": "yarn && ng build mc-libs-integration --configuration=production --progress=false --delete-output-path true",
    "servewab": "yarn && ng serve mc-web-app -c build",
    "servewal": "set NODE_OPTIONS=--max_old_space_size=8192 && yarn && ng serve mc-web-app -c local",
    "testwa": "yarn && ng test mc-web-app --source-map=false",
    "testwa-wsi": "yarn && node_modules\\.bin\\ng test mc-web-app --source-map=false --karma-config=\".\\apps\\mc-web-app\\karma.local.conf.js\"",
    "test-build-config-wa": "node_modules\\.bin\\ng test mc-web-app --source-map=false --karma-config=\".\\apps\\mc-web-app\\karma.build.conf.js\"",
    "dist-build-wa-build": "set NODE_OPTIONS=--max_old_space_size=8192 && yarn && ng build mc-web-app --configuration=production --progress=false --output-path \"..\\Server\\WebSites\\MachiningCloudWebApp\\wwwroot\" --delete-output-path true",
    "dist-build-wa-compress": "..\\..\\Tools\\bin\\ps compress ..\\Server\\WebSites\\MachiningCloudWebApp\\wwwroot \"*.js *.css *.txt *.svg *.ttf\" && del /F ..\\Server\\WebSites\\MachiningCloudWebApp\\wwwroot\\index.html",
    "dist-build-wa": "npm run dist-build-wa-build && npm run dist-build-wa-compress",
    "dist-build-wa-dod-build": "set NODE_OPTIONS=--max_old_space_size=8192 && yarn && ng build mc-web-app --configuration=dodprod --progress=false --output-path \"..\\Server\\WebSites\\MachiningCloudWebApp\\wwwroot\" --delete-output-path true",
    "dist-build-wa-dod": "npm run dist-build-wa-dod-build && npm run dist-build-wa-compress",
    "test-build-config-a": "node_modules\\.bin\\ng test accounts --source-map=false --karma-config=\".\\apps\\accounts\\karma.build.conf.js\"",
    "pre-build-a": "yarn && node_modules\\.bin\\tsc -p ./apps/accounts/tsconfig.server-path-helper.json",
    "dist-build-a": "npm run pre-build-a && ng build accounts --configuration=production --progress=false --output-path \"..\\Server\\WebSites\\MachiningCloudAccountsClient\\wwwroot\" --delete-output-path true",
    "analyze": "yarn && ng build mc-web-app --configuration=production --stats-json && webpack-bundle-analyzer dist/apps/mc-web-app/stats.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "15.2.7",
    "@angular/cdk": "14.2.7",
    "@angular/common": "15.2.7",
    "@angular/compiler": "15.2.7",
    "@angular/core": "15.2.7",
    "@angular/forms": "15.2.7",
    "@angular/material": "14.2.7",
    "@angular/platform-browser": "15.2.7",
    "@angular/platform-browser-dynamic": "15.2.7",
    "@angular/router": "15.2.7",
    "@ngrx/effects": "15.4.0",
    "@ngrx/store": "15.4.0",
    "@ngx-translate/core": "14.0.0",
    "@ngx-translate/http-loader": "7.0.0",
    "@stripe/stripe-js": "^1.5.0",
    "@types/pako": "2.0.0",
    "@types/quill": "2.0.10",
    "@types/three": "0.150.2",
    "add": "2.0.6",
    "ag-grid-angular": "29.3.5",
    "ag-grid-community": "29.3.5",
    "ag-grid-enterprise": "29.3.5",
    "angular-resize-event": "3.2.0",
    "angular2-toaster": "11.0.1",
    "animate.css": "4.1.1",
    "arrive": "2.4.1",
    "blueimp-canvas-to-blob": "3.29.0",
    "bootstrap": "4.6.1",
    "bootstrap-material-design": "4.1.3",
    "bootstrap-notify": "3.1.3",
    "bootstrap-tagsinput": "0.7.1",
    "change-case": "4.1.2",
    "chartist": "^1.3.0",
    "core-js": "3.30.1",
    "domready": "1.0.8",
    "file-saver": "2.0.5",
    "font-awesome": "4.7.0",
    "intersection-observer": "0.12.2",
    "jasny-bootstrap": "4.0.0",
    "jquery": "3.6.4",
    "jquery-validation": "1.19.5",
    "lodash": "4.17.21",
    "material-icons": "1.13.5",
    "moment": "2.29.4",
    "moment-timezone": "0.5.43",
    "ng-in-viewport": "15.0.1",
    "ngx-mat-select-search": "5.0.0",
    "ngx-moment": "6.0.2",
    "ngx-order-pipe": "2.2.0",
    "ngx-quill": "20.0.1",
    "normalizr": "3.6.2",
    "nouislider": "15.7.0",
    "pako": "2.1.0",
    "path": "0.12.7",
    "perfect-scrollbar": "1.5.5",
    "popper": "1.0.1",
    "popper.js": "1.16.1",
    "quill": "1.3.7",
    "quill-delta-to-html": "0.12.1",
    "reflect-metadata": "0.1.13",
    "roboto-fontface": "0.10.0",
    "rxjs": "7.8.0",
    "tassign": "1.0.0",
    "three": "0.151.3",
    "three-ply-loader": "1.0.0",
    "tslib": "^2.5.0",
    "typescript-collections": "1.3.3",
    "ua-parser-js": "1.0.35",
    "validate": "5.2.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.2.6",
    "@angular-devkit/schematics": "^15.2.6",
    "@angular/cli": "15.2.6",
    "@angular/compiler-cli": "15.2.7",
    "@angular/language-service": "15.2.7",
    "@ngrx/store-devtools": "15.4.0",
    "@nrwl/angular": "15.9.2",
    "@nrwl/workspace": "15.9.2",
    "@types/bootstrap": "4.6.1",
    "@types/chartist": "^1.0.0",
    "@types/file-saver": "2.0.5",
    "@types/jasmine": "~4.3.1",
    "@types/jasminewd2": "2.0.10",
    "@types/lodash": "4.14.194",
    "@types/node": "18.15.12",
    "codelyzer": "^6.0.0",
    "dotenv": "16.0.3",
    "eslint": "^8.38.0",
    "jasmine-core": "~4.6.0",
    "jasmine-marbles": "^0.9.2",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-ie-launcher": "1.0.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "karma-junit-reporter": "2.0.1",
    "karma-parallel": "0.3.1",
    "karma-teamcity-reporter": "1.1.0",
    "prettier": "2.8.7",
    "protractor": "~7.0.0",
    "ts-node": "10.9.1",
    "typescript": "~4.9.5",
    "webpack-bundle-analyzer": "^4.8.0"
  }
}
```

This is my package.json file

**Comment by sguin3395** [comment]
@KillerCodeMonkey Did you find a workaround for this one? I created an app with just Angular 15.2.7 and ngx-quill@20.0.0 which is working perfectly fine.

However, it isn't working in this case.

**Comment by KillerCodeMonkey** [comment]
sorry i have a bunch of work these days. could you create a minimal repo where i can reproduce the issue?

**Comment by sguin3395** [comment]
@KillerCodeMonkey I have been a little busy with a  few other stuff. Will be putting up a repo where this issue is recreated.

**Comment by KillerCodeMonkey** [comment]
@sguin3395 any updates?

**Comment by KillerCodeMonkey** [comment]
closed due to inactivity
