### ISSUE TITLE
Upgrading from 23.0.3 to 25.3.2

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [KillerCodeMonkey/ngx-quill#1845]
Hello there, just wondering is there anything specific that one needs to do while upgrading from Quill v1 to Quill v2 ? 

With my current setup after upgrading I get this error: 

`Uncaught TypeError: this.quillEditor.getSemanticHTML is not a function
    at _QuillEditorComponent.textChangeHandler (ngx-quill.mjs:281:35)
    at Object.next (ngx-quill.mjs:659:14)
    at ConsumerObserver2.next (Subscriber.js:96:33)
    at Subscriber2._next (Subscriber.js:63:26)
    at Subscriber2.next (Subscriber.js:34:18)
    at Emitter2.handler (fromEvent.js:41:31)
    at Emitter2.emit (quill.js:8665:33)
    at Emitter2.emit (quill.js:1943:99)
    at Quill2.modify (quill.js:1678:39)
    at Quill2.insertText (quill.js:1447:21)`

` here -->   let html = this.quillEditor.getSemanticHTML();`

Thanks a lot for the effort put into this :D

**Comment by KillerCodeMonkey** [comment]
in general follow the readme as always. i think you installed @types/quill which is not needed anymore.
so first of all you should read and follow https://quilljs.com/docs/upgrading-to-2-0
and then check the readme here for some special things.

In general in ngx-quill only some properties were removed because they are no longer supported by quilljs, but the compiler would notify you ;-)

**Comment by AbdulTheActivePiecer** [comment]
Got it, my issue was that I only upgraded ngx-quill, didn't upgrade quill on its own, cheers.
