### ISSUE TITLE
Uncaught Error: Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by chriseenberg** [KillerCodeMonkey/ngx-quill#3]
Hi.

I've just downloaded your component and im trying to make it work. I've added the component to my appModule as explained in the ReadMe file.

i get this error when trying to transpile my code:
```
angular 2/angular-seed/angular-webpack/node_modules/ng2-quill-editor/quillEditor.component.ts:81:57
Property 'assign' does not exist on type 'ObjectConstructor'.
```

i also get a bunch of errors, like this one:
```
Uncaught Error: Expected 'styles' to be an array of strings.
at assertArrayOfStrings (eval at (http://localhost:8081/vendor.js:95:2)
```

Most of the errors occur in the vendor.ts file.

I had to set the `"noImplicitAny": false` to false to avoid a whole bunch of other errors regarding implicitly type any.

Is there any fix to these errors? Am i missing something?

I'm running with typescript version 2.0.10 - angular version ~2.2.0

Kind regards Chris

**Comment by KillerCodeMonkey** [comment]
i am using angular 2.2.3 in the latest release. please try it with the correct versions. 
If this does not solves the problem, let me know.

Cheers

**Comment by chriseenberg** [comment]
Just did a strict versioning with npm -> no updates on 2.2.3, still getting this:

`compiler.umd.js?9df7:441 Uncaught Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:441:21)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14511:15)
    at CompileMetadataResolver._loadDirectiveMetadata (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14446:44)
    at eval (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14712:42)
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14702:56)
    at CompileMetadataResolver._loadNgModuleSummary (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14615:33)
    at eval (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14673:57)
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14660:51)
    at CompileMetadataResolver.loadNgModuleMetadata (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:14625:31)
    at RuntimeCompiler._loadModules (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:17420:43)
    at RuntimeCompiler._compileModuleAndComponents (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:17390:37)
    at RuntimeCompiler.compileModuleAsync (eval at <anonymous> (http://localhost:8081/vendor.js:95:2), <anonymous>:17380:23)
    at PlatformRef_._bootstrapModuleWithZone (eval at <anonymous> (http://localhost:8081/vendor.js:101:2), <anonymous>:6454:29)
    at PlatformRef_.bootstrapModule (eval at <anonymous> (http://localhost:8081/vendor.js:101:2), <anonymous>:6436:25)
    at Object.eval (eval at <anonymous> (http://localhost:8081/app.js:88:2), <anonymous>:8:53)
    at eval (eval at <anonymous> (http://localhost:8081/app.js:88:2), <anonymous>:10:30)
    at Object.<anonymous> (http://localhost:8081/app.js:88:2)
    at __webpack_require__ (http://localhost:8081/polyfills.js:51:30)
    at Object.<anonymous> (http://localhost:8081/app.js:6:19)
    at __webpack_require__ (http://localhost:8081/polyfills.js:51:30)
    at webpackJsonpCallback (http://localhost:8081/polyfills.js:22:20)
    at http://localhost:8081/app.js:1:1`

i can try to add the version bump again, and see but that's what i had before, doubt that will do any good.

Kind regards - and thanks for getting back to me

**Comment by KillerCodeMonkey** [comment]
meeeehhh .. okay.

i will try to update dependencies to newest cli beta and quilljs (huge bugfixes).
And will come back later.

**Comment by chriseenberg** [comment]
Thank you so much! :)

**Comment by KillerCodeMonkey** [comment]
sooo i have updated cli to latest beta and increased + fixed rxjs and @angular versions -.-.
This incompatiblility suuuuuuucks *narf

I renamed the repo to ngx-quill, because of the new versioning of angular >=2.
See the 0.1.0 release

**Comment by chriseenberg** [comment]
Thanks - i'll try it out right away :)

**Comment by chriseenberg** [comment]
Hi again.

After updating to the latest version, i've come to an end with a new error. I've tried switching around the versions of angular without luck. I still end up with this error: `Unexpected value 'QuillModule' imported by the module 'AppModule'`
I'm not entirely sure where to go from here. Can you tell me the exact version of Angular 2 you are using?

i've tried with 2.2.3 - 2.2.4 / 2.3.x / 2.4.x

Kind regards Chris

**Comment by KillerCodeMonkey** [comment]
you can find anything important in my package.json --> https://github.com/KillerCodeMonkey/ngx-quill/blob/develop/package.json ;)

So with latest angular-cli i use angular stuff v2.3.1

But it sounds you have not installed quill 1.1.9

**Comment by chriseenberg** [comment]
Do i need to download quill as a separate module?
Cause if this is the case, i missed that one.. :D

-Chris

**Comment by KillerCodeMonkey** [comment]
i do not know you setup, but in general it is a dependency for ngx-quill, so you do not have to do it.

But i see --> you added the `QuillModule` to your AppModule, but you do not imported the module like

```
import { QuillModule } from 'ngx-quill/src/quill/quill.module';
```

**Comment by chriseenberg** [comment]
I think i finally found my error. Is this npm module an entire project to be run? Because i have an existing project that im trying to apply it to, which would explain why it does not work :)

Kind regards Chris

**Comment by KillerCodeMonkey** [comment]
It is an complete project, but only to combine a demo-page with the module. you can use this as external module --> in src-folder is the whole project. But there are two modules --> app and quill.

App uses quill to present a demo, how to use it :).

this AppModule is my demo page.
