### ISSUE TITLE
ng-bootstrap

### ISSUE THREAD

**Issue by selvam326** [KillerCodeMonkey/ngx-quill#303]
I am getting the following error while running ng serve command.

Angular CLI: 7.1.3
Node: 10.14.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.3
@angular-devkit/core         7.1.3
@angular-devkit/schematics   7.1.3
@schematics/angular          7.1.3
@schematics/update           0.11.3
rxjs                         6.3.3
typescript                   3.1.6

ERROR in Error: Metadata version mismatch for module c:/calsoft/node_modules/@ng
-bootstrap/ng-bootstrap/index.d.ts, found version 4, expected 3, resolving symbo
l SharedModule in c:/calsoft/src/app/shared/shared.module.ts, resolving symbol S
haredModule in c:/calsoft/src/app/shared/shared.module.ts, resolving symbol Shar
edModule in c:/calsoft/src/app/shared/shared.module.ts
    at syntaxError (c:\calsoft\node_modules\@angular\compiler\bundles\compiler.u
md.js:1729:34)
    at simplifyInContext (c:\calsoft\node_modules\@angular\compiler\bundles\comp
iler.umd.js:24979:23)
    at StaticReflector.simplify (c:\calsoft\node_modules\@angular\compiler\bundl
es\compiler.umd.js:24991:13)
    at StaticReflector.annotations (c:\calsoft\node_modules\@angular\compiler\bu
ndles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (c:\calsoft\node_modules\@angular\compiler-cli\src\n
gtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (c:\calsoft\node_modules\@angular\comp
iler-cli\src\ngtools_impl.js:109:26)
    at c:\calsoft\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (c:\calsoft\node_modules\@angular\comp
iler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (c:\calsoft\node_modules\@angular\compiler-
cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (c:\calsoft\node_modules
\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (c:\calsoft\node_modules\@ngtools\web
pack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (c:\calsoft\node_mo
dules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Please help me to fix this issue.

**Comment by KillerCodeMonkey** [comment]
Why do you ask here?
`Metadata version mismatch for module c:/calsoft/node_modules/@ng
-bootstrap/ng-bootstrap/index.d.ts`

so i think this is a problem with ng-bootstrap
https://github.com/ng-bootstrap/ng-bootstrap#dependencies

so maybe you are using the wrong version of it? you need v4 for angular v7
