### ISSUE TITLE
unexpected token error

### ISSUE THREAD

**Issue by rashmim00** [KillerCodeMonkey/ngx-quill#555]
Hi, 
I am trying to install ngx-quill with angular 6 and I run into "unexpected token <" error.
I followed the readme and mostly I am missing something. Just outlining the steps I did:
-  I have npm install quill and ngx-quill
- Added bubble.css and snow.css in index file
- Modify systemjs.config 
- Add import in app.module and in imports 

What am I missing here. 

Thanks.

**Comment by KillerCodeMonkey** [comment]
Please provide Demo Repo or Stackblitz.

You could check Out my example repo linked in the readme. IT IS working
there. Just Clone IT and downgrade the angular deps to angular 6.

Or remove ngx quill from your Project and Check If it is working without IT.


Rashmi Maheshwari <notifications@github.com> schrieb am Mi., 2. Okt. 2019,
20:02:

**Comment by rashmim00** [comment]
Thanks for your quick reply... If i remove ngx quill from my project then its working. 
I will try with  https://github.com/killerCodeMonkey/ngx-quill-example.

**Comment by KillerCodeMonkey** [comment]
You should Not use systemjs at all. Using the angular cli is the
recommended way to build angular Apps :).

Rashmi Maheshwari <notifications@github.com> schrieb am Mi., 2. Okt. 2019,
20:36:

**Comment by rashmim00** [comment]
hmmm... my whole project is set that way... Is there another way to include quill. Can I import * from ngx-quill and use the quillEditor object. 

The example is failing on angular-webkit -
 $ ng serve
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\src\workspace\workspace.js:210:42)
    at MergeMapSubscriber._tryNext (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MapSubscriber._next (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\map.js:52:26)
    at MapSubscriber.Subscriber.next (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:64:18)
    at SwitchMapSubscriber.notifyNext (C:\ifolder\iroot\quillexample\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:77:26)

**Comment by KillerCodeMonkey** [comment]
Could you create a Demo Repo only ngx-quill and systemjs ? So i can Check
the Code?

Rashmi Maheshwari <notifications@github.com> schrieb am Mi., 2. Okt. 2019,
21:38:

**Comment by rashmim00** [comment]
This error is with angular 6.0.9 and rxjs as 6.2.1.

If I run your example as is then it works.

**Comment by KillerCodeMonkey** [comment]
yeah because you have to change the angular-devkit version as well.

i created a branch for you of my example repo with angular 6 (but you should totally upgrade to angular 8 - because angular 9 is mostly there ;-).

https://github.com/KillerCodeMonkey/ngx-quill-example/tree/angular-6

And as you can see https://github.com/KillerCodeMonkey/ngx-quill#compatibility-to-angular-versions angular 6 support will be dropped next month.
