### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by MaximDomanov** [KillerCodeMonkey/ngx-quill#620]
Hi, I have a problem. If I use yarn to install dependencies I have the error below. If I use npm everything is ok. 

  "dependencies": {
    "@angular/animations": "^8.2.6",
    "@angular/cdk": "^8.2.0",
    "@angular/cli": "^8.3.4",
    "@angular/common": "^8.2.6",
    "@angular/compiler": "^8.2.6",
    "@angular/core": "^8.2.6",
    "@angular/forms": "^8.2.6",
    "@angular/material": "^8.2.0",
    "@angular/material-moment-adapter": "^8.2.0",
    "@angular/platform-browser": "^8.2.6",
    "@angular/platform-browser-dynamic": "^8.2.6",
    "@angular/platform-server": "^8.2.6",
    "@angular/router": "^8.2.6",
    "@ngx-loading-bar/core": "^4.2.0",
    "@ngx-loading-bar/router": "^4.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "actioncable": "^5.2.3",
    "angular-svg-icon": "^8.0.0",
    "angular2-text-mask": "^9.0.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.0",
    "dotenv": "^8.0.0",
    "file-saver": "^2.0.2",
    "hammerjs": "^2.0.8",
    "http-status-codes": "^1.3.0",
    "moment": "^2.20.1",
    "ng5-slider": "^1.2.4",
    "ngx-clipboard": "^12.2.1",
    "ngx-image-cropper": "^1.0.1",
    "ngx-moment": "^3.4.0",
    "ngx-quill": "^7.3.9",
    "ngx-take-until-destroy": "^5.4.0",
    "quill": "^1.3.7",
    "raven-js": "^3.26.3",
    "rxjs": "^6.3.0",
    "smoothscroll-polyfill": "^0.4.3",
    "tslib": "^1.10.0",
    "typescript-memoize": "^1.0.0-alpha.3",
    "zone.js": "~0.9.1"
  }

ng build --aot --prod
  
ERROR in ./node_modules/ngx-quill/fesm2015/ngx-quill.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:230:35)
    at checkNodeForDecorators (/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:53:21)
    at visitNodes (/web/node_modules/typescript/lib/typescript.js:16631:30)
    at Object.forEachChild (/web/node_modules/typescript/lib/typescript.js:16859:24)
    at transformer (/web/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:39:16)
    at transformSourceFileOrBundle (/web/node_modules/typescript/lib/typescript.js:67384:57)
    at transformation (/web/node_modules/typescript/lib/typescript.js:83586:24)
    at transformRoot (/web/node_modules/typescript/lib/typescript.js:83606:82)
    at Object.map (/web/node_modules/typescript/lib/typescript.js:499:29)
    at Object.transformNodes (/web/node_modules/typescript/lib/typescript.js:83593:30)
    at emitJsFileOrBundle (/web/node_modules/typescript/lib/typescript.js:84089:32)
    at emitSourceFileOrBundle (/web/node_modules/typescript/lib/typescript.js:84043:13)
    at forEachEmittedFile (/web/node_modules/typescript/lib/typescript.js:83832:34)
    at Object.emitFiles (/web/node_modules/typescript/lib/typescript.js:84026:9)
    at emitWorker (/web/node_modules/typescript/lib/typescript.js:89951:33)
    at /web/node_modules/typescript/lib/typescript.js:89912:66

**Comment by KillerCodeMonkey** [comment]
please use the issue search next time:

https://github.com/KillerCodeMonkey/ngx-quill/issues/619
https://github.com/KillerCodeMonkey/ngx-quill/issues/614

depends if you are already have a packae-lock file there or yarn lock different versions of you dependencies are installed.
