### ISSUE TITLE
angular build ngx-quill error

### ISSUE THREAD

**Issue by wuaries** [KillerCodeMonkey/ngx-quill#631]
ERROR in ./node_modules/ngx-quill/fesm5/ngx-quill.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (E:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (E:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (E:\angular-electron\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (E:\angular-electron\node_modules\typescript\lib\typescript.js:16857:24)
    at checkNodeForDecorators (E:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (E:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (E:\angular-electron\node_modules\typescript\lib\typescript.js:16752:21)
    at checkNodeForDecorators (E:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (E:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (E:\angular-electron\node_modules\typescript\lib\typescript.js:16809:24)
    at checkNodeForDecorators (E:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (E:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (E:\angular-electron\node_modules\typescript\lib\typescript.js:16820:24)
    at checkNodeForDecorators (E:\angular-electron\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (E:\angular-electron\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (E:\angular-electron\node_modules\typescript\lib\typescript.js:16716:21)[0m

angular cli version: 8.3.3
ngx-quill version:7.3.9
quill version:1.3.7

**Comment by KillerCodeMonkey** [comment]
please use the issue search first before opening new issues.

https://github.com/KillerCodeMonkey/ngx-quill/issues/619
https://github.com/KillerCodeMonkey/ngx-quill/issues/620
https://github.com/KillerCodeMonkey/ngx-quill/issues/573
