### ISSUE TITLE
[prod build] TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by indraraj26** [KillerCodeMonkey/ngx-quill#635]
Angular 8 without IVY

Error: 
```

ERROR in ./node_modules/ngx-quill/fesm2015/ngx-quill.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\customer\ng-customer-lms\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (D:\customer\ng-customer-lms\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (D:\customer\ng-customer-lms\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (D:\customer\ng-customer-lms\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (D:\customer\ng-customer-lms\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (D:\customer\ng-customer-lms\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (D:\customer\ng-customer-lms\node_modules\typescript\lib\typescript.js:16599:21)
```

**Comment by KillerCodeMonkey** [comment]
please use the issue search... there are similar issues and also some fixes. 

btw. my demo repo is using ivy and it is working
