### ISSUE TITLE
ngx-quill is breaking on aot build

### ISSUE THREAD

**Issue by mhamri** [KillerCodeMonkey/ngx-quill#708]
I just update to ngx-quill version 7.3.11 and got this problem on aot build

our previous version that build correctly was 7.3.1

we are using angular 8.2.7 and typescript 3.5.3

```
ERROR in C:/repo/Applicat/Applicat/src/Company.Applicat.Frontend/ClientApp/node_modules/ngx-quill/fesm5/ngx-quill.js
Module build failed (from C:/repo/Applicat/Applicat/src/Company.Applicat.Frontend/ClientApp/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16857:24)
    at checkNodeForDecorators (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16752:21)
    at checkNodeForDecorators (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16809:24)
    at checkNodeForDecorators (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16820:24)
    at checkNodeForDecorators (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:44:31)
    at visitNode (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16622:24)
    at Object.forEachChild (C:\repo\Applicat\Applicat\src\Company.Applicat.Frontend\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! axl@0.0.0 build: `cross-env NODE_OPTIONS=--max-old-space-size=8192 ng build Applicat "--configuration=production"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the axl@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\UserName\AppData\Roaming\npm-cache\_logs\2020-01-03T10_51_04_725Z-debug.log
```

**Comment by KillerCodeMonkey** [comment]
depends on your build process.

i have no problems in my demo app/repo even with ivy renderer

**Comment by KillerCodeMonkey** [comment]
Check angular, angular-cli and typescript issues. There are many of that type.

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/573
https://github.com/KillerCodeMonkey/ngx-quill/issues/631
