### ISSUE TITLE
isPlatformServer check not working and quill is trying to use dom on server in angular Universal application, angular 9

### ISSUE THREAD

**Issue by NiveshSinghChauhan** [KillerCodeMonkey/ngx-quill#871]
**These are the dependencies in my package.json**
`"dependencies": {
    "@angular/animations": "~9.0.5",
    "@angular/common": "~9.0.5",
    "@angular/compiler": "~9.0.5",
    "@angular/core": "~9.0.5",
    "@angular/forms": "~9.0.5",
    "@angular/platform-browser": "~9.0.5",
    "@angular/platform-browser-dynamic": "~9.0.5",
    "@angular/platform-server": "~9.0.5",
    "@angular/router": "~9.0.5",
    "@nguniversal/express-engine": "^9.0.2",
    "body-parser": "^1.19.0",
    "chart.js": "^2.9.3",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.5",
    "date-fns": "^2.12.0",
    "express": "^4.15.2",
    "highlight.js": "^10.0.1",
    "immutable": "^4.0.0-rc.12",
    "ngx-infinite-scroll": "^8.0.2",
    "ngx-quill": "^8.1.7",
    "numeral": "^2.0.6",
    "preboot": "^7.0.0",
    "quill": "^1.3.7",
    "rxjs": "~6.5.4",
    "shortid": "^2.2.15",
    "timeago.js": "^4.0.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.5",
    "@angular/cli": "~9.0.5",
    "@angular/compiler-cli": "~9.0.5",
    "@angular/language-service": "~9.0.5",
    "@nguniversal/builders": "^9.0.2",
    "@types/cookie-parser": "^1.4.2",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }`

compiling and builds are successfull but when i serve universal app and access the endpoint thorws this error
`ERROR { Error: Uncaught (in promise): ReferenceError: document is not defined
ReferenceError: document is not defined
    at Object.<anonymous> (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:5144391)
    at __webpack_require__ (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:4948492)
    at Object.<anonymous> (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:4972149)
    at __webpack_require__ (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:4948492)
    at Object.<anonymous> (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:5094111)
    at __webpack_require__ (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:4948492)
    at Object.<anonymous> (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:5200894)
    at __webpack_require__ (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:4948492)
    at Object.<anonymous> (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:5259653)
    at __webpack_require__ (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:4948492)
    at resolvePromise (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3737617)
    at resolvePromise (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3736594)
    at D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3739421       
    at ZoneDelegate.invokeTask (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3728721)
    at Object.onInvokeTask (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:4280670)
    at ZoneDelegate.invokeTask (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3728611)
    at Zone.runTask (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3721286)
    at drainMicroTaskQueue (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3732329)
    at ZoneTask.invokeTask (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3730370)
    at Server.ZoneTask.options.useG.invoke (D:\PROJECTS\thesocialcomment\frontend\dist\frontend\server\main.js:1:3730135)`
this error is only thrown on those module where ngx quill is imported

can anybody tell me whats the problem and how to fix this

**Comment by KillerCodeMonkey** [comment]
i am building my app with ng-packagr and it seems that it hoists the "require('quill')" part to the top of the module.

So it imports quilljs everytime even on serverside.

When you know hot to avoid it, let me know.

**Comment by jdgamble555** [comment]
In Angular Universal you need to use the webpack for this to work: [#91](https://github.com/KillerCodeMonkey/ngx-quill/issues/91#issuecomment-620019584)

**Comment by KillerCodeMonkey** [comment]
and i added a new block about it to the readme:
https://github.com/KillerCodeMonkey/ngx-quill/blob/master/README.md#angular-universal
