### ISSUE TITLE
Build failed with ngcc esm5

### ISSUE THREAD

**Issue by Chiff** [KillerCodeMonkey/ngx-quill#963]
`ngcc` on `ngx-quill` with `esm5` fails my jenkins build

console output
```
[INFO] --- frontend-maven-plugin:1.6:install-node-and-yarn (yarn-run-build) @ sz-web-fe ---
[INFO] Node v12.6.0 is already installed.
[INFO] Yarn 1.17.3 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:yarn (yarn-run-build) @ sz-web-fe ---
[INFO] Running 'yarn run build' in /var/jenkins_home/workspace/my-secret-project/sz-web-fe
[INFO] yarn run v1.17.3
[INFO] $ yarn install && ng build --project=sz-web --configuration production && ng build --project=sz-admin --configuration production
[INFO] [1/4] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ ngcc --properties esm5 browser module main --first-only --create-ivy-entry-points
[INFO] Compiling @ng-bootstrap/ng-bootstrap : esm5 as esm5
[INFO] Compiling @angular/platform-browser-dynamic/testing : esm5 as esm5
[INFO] Compiling ngx-quill : module as esm5
[ERROR] [33mWarning:[0m Invalid constructor parameter decorator in /var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/ngx-quill/fesm2015/ngx-quill.js:
[ERROR]  () => [
[ERROR]     { type: undefined, decorators: [{ type: Inject, args: [QUILL_CONFIG_TOKEN,] }] }
[ERROR] ]
[ERROR] Error: Error on worker #3: Error: getInternalNameOfClass() called on a non-ES5 class: expected QuillService to have an inner class declaration
[ERROR]     at Esm5ReflectionHost.getInternalNameOfClass (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/host/esm5_host.js:88:23)
[ERROR]     at DelegatingReflectionHost.getInternalNameOfClass (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:89:34)
[ERROR]     at extractInjectableMetadata (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:125:69)
[ERROR]     at InjectableDecoratorHandler.analyze (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:66:24)
[ERROR]     at NgccTraitCompiler.TraitCompiler.analyzeTrait (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
[ERROR]     at analyze (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:297:58)
[ERROR]     at _loop_1 (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:319:21)
[ERROR]     at NgccTraitCompiler.TraitCompiler.analyzeClass (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:325:35)
[ERROR]     at NgccTraitCompiler.analyzeFile (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.js:47:26)
[ERROR]     at DecorationAnalyzer.analyzeProgram (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:134:39)
[ERROR]     at ClusterMaster.onWorkerMessage (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:194:27)
[ERROR]     at /var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:54:95
[ERROR]     at ClusterMaster.<anonymous> (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:292:57)
[ERROR]     at step (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/tslib/tslib.js:139:27)
[ERROR]     at Object.next (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/tslib/tslib.js:120:57)
[ERROR]     at /var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/tslib/tslib.js:113:75
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at Object.__awaiter (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/tslib/tslib.js:109:16)
[ERROR]     at EventEmitter.<anonymous> (/var/jenkins_home/workspace/my-secret-project/sz-web-fe/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:286:32)
[ERROR]     at EventEmitter.emit (events.js:203:13)
[ERROR] error Command failed with exit code 1.
```

It is weird behavior because when i run it on my pc it works just fine
`ngcc` with `es2015` works also fine on jenkins

Packages
    "@angular/...": "~9.1.0",
    "ngx-quill": "^12.0.1",
    "quill": "^1.3.7",
    "quill-delta": "^4.2.2",
    "@types/quill": "^1.3.10",
    "@types/quill-delta": "https://github.com/maximkornilov/types-quill-delta/tarball/master",

**Comment by KillerCodeMonkey** [comment]
could you please try angular v10 or ngx-quill < 12?

**Comment by Chiff** [comment]
Downgrading `ngx-quill` to v `11.1` fixed the problem while using `ngcc esm5`

### Recap
ngcc | machine | quill version | result
--- | --- | --- | ---
esm5 | local | 12 | **ok**
esm5 | jenkins | 12 | **fail**
es2015 | local | 12 | **ok**
es2015 | jenkins | 12 | **ok**
esm5 | local | 11.1 | **ok**
esm5 | locjenkinsal | 11.1 | **ok**


Thanks for fast response!
